### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified when running keyfinder on windows machine

### ISSUE THREAD

**Issue by ritesh-symantec** [CERTCC/keyfinder#2]
below is the error I am getting when executing on a windows machine. I have Python 3.7.8 installed with all the dependencies

PS D:\Python\keyfinder-master> python.exe .\keyfinder.py -d --key '.\New folder\reliance.key'
Checking key .\New folder\reliance.key
Analyzing .\New folder\reliance.key with password ""...
Selecting .\New folder\reliance.key
Opening .\New folder\reliance.key ...
Found PEM pkcs5 PRIVATE key: .\New folder\1.key
Analyzing and getting sha256...
PEM encoded key...
Traceback (most recent call last):
  File ".\keyfinder.py", line 1488, in <module>
    check_keyfile(args.check_keyfile)
  File ".\keyfinder.py", line 1341, in check_keyfile
    keydict = analyze_keyfile(keypath, keyfiletype)
  File ".\keyfinder.py", line 1113, in analyze_keyfile
    keydict.update(decodekeydata(keyfile, keydata))
  File ".\keyfinder.py", line 824, in decodekeydata
    kd = get_sha256(keyfile, keydata)
  File ".\keyfinder.py", line 304, in get_sha256
    timeout=2, stderr=FNULL)
  File "D:\Python\lib\subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "D:\Python\lib\subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "D:\Python\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "D:\Python\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by hktari** [comment]
same issue here

**Comment by wdormann** [comment]
As the error message indicates, the problem is on line 304 of keyfinder.py
This is where the program `openssl` is executed.

I presume that you don't have the openssl executable in your path?
